name: CI/CD Pipeline

on:
  push:
    branches: [develop, production]
  pull_request:
    branches: [develop, production]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install Dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        # with:
        #   version: 10.18.2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

  build:
    runs-on: ubuntu-latest
    name: Build Application
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        # with:
        #   version: 10.18.2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build
